USERNAME_TAKEN = "Username telah digunakan"
PASSWORD_INCORRECT = "Password yang Anda masukkan salah"
ERROR_DATA_NOT_FOUND = "Data tidak ditemukan"
ERROR_DATA_ID_NOT_EXIST = "Data dengan id {0} tidak ditemukan"
ERROR_MODEL_ID_NOT_EXIST = "{0} dengan id {1} tidak ditemukan"
ERROR_FACULTY_NAME_CODE_EXIST = "Nama atau kode fakultas telah digunakan"
SUCCESS_DATA_DELETED = "Data berhasil dihapus"
ERROR_INTERNAL_SERVER_ERROR = "Terjadi Kesalahan"
ROLE_INVALID = "Role tidak valid"

MODEL_USER = "User"
MODEL_LECTURER = "Dosen"
MODEL_STUDENT = "Mahasiswa"
MODEL_COURSE = "Mata Kuliah"
MODEL_SEMESTER = "Semester"
MODEL_DEPARTMENT = "Departemen"
MODEL_FACULTY = "Fakultas"
MODEL_MEETING = "Pertemuan"
