from .crud_user import user
from .crud_role import role
from .crud_student import student
from .crud_faculty import faculty
from .crud_department import department
from .crud_semester import semester
from .crud_schedule import schedule
from .crud_course import course
from .crud_meeting import meeting
