from .crud_user import user
from .crud_role import role
from .crud_student import student
from .crud_lecturer import lecturer
from .crud_faculty import faculty
from .crud_department import department
from .crud_semester import semester
from .crud_schedule import schedule
from .crud_course import course
from .crud_meeting import meeting
from .crud_attendance import attendance
from .crud_site_setting import site_setting
