from .user import User
from .permission import Permission
from .role import Role
from .user_role import user_role
from .role_permission import RolePermission
from .semester import Semester
from .faculty import Faculty
from .department import Department
from .course import Course
from .schedule import Schedule
from .meeting import Meeting
from .student import Student
from .lecturer import Lecturer
from .course_student import CourseStudent
from .course_lecturer import CourseLecturer
from .attendance import Attendance
